on:
  pull_request:
jobs:
  fail_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check firt
        run: echo "ok"
      - name: display string
        run: exit 0
      - name: test
        run: echo "fail"
  fail_job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check firt
        run: echo "ok"
      - name: display string
        run: exit 1
      - name: test
        run: echo "fail"
  slack-notification:
    name: Slack notification
    #needs: [fail_job, fail_job2]
    if: failure() 
    #&& (needs.fail_job2.result == 'failure')
    runs-on: ubuntu-latest
    steps:
      - name: slack alert
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.TEST_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: testw failed on ${{ github.repository }}, <@U04BECLQS4A>
          SLACK_TITLE: FAILED
          SLACK_USERNAME: Actions
  
