on:
  pull_request:
jobs:
  fail_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check firt
        run: echo "ok"
      - name: display string
        run: exit 0
      - name: test
        run: echo "ok"
  fail_job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check firt
        run: echo "ok"
      - name: display string
        run: exit 1
      - name: test
        run: echo "fail"
  slack-notification:
    name: Slack notification
    needs: [fail_job, fail_job2]
    if: failure() 
    #&& (needs.fail_job2.result == 'failure')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test-url
        id: test-url
        run: |
          url_test=https://github.com/dheerajmavilla/sample-repo/actions/runs/3494495755/jobs/5850319104
          echo "url_test=$url_test" >> $GITHUB_OUTPUT
      - name: test-string
        run: echo ${{ steps.test-url.outputs.url_test }}
      - name: slack alert
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.TEST_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: <${{ steps.test-url.outputs.url_test }}> \
                         testw failed on ${{ github.repository }}, <@U04BECLQS4A>
          SLACK_TITLE: FAILED, <${{ steps.test-url.outputs.url_test }}>
          SLACK_USERNAME: Actions
  
